### ISSUE TITLE
Datos del Sitio, del Administrador(a) y de ejemplo no están documentados en el Foro de Jokte!

### ISSUE THREAD

**Issue by apradoc** [JokteLatinoamerica/jokte-cms#57]
Los enlaces desde la instalación están correctamente asignados pero en el foro no existe información al respecto por básica o tácita que sea. Se refiere este issue también a ls moderadores del foro

**Comment by snaphuman** [comment]
@apradoc veo que este no es un incidente propiamente funcional de Jokte!. Es posible gestionarlo a través de la lista de correo de la asamblea juuntos, para que se complete la información de los datos del sitio, administrado y de ejemplo en el foro?

Quedaría sólamente este incidente por solucionar para completar el hito para la versión 1.3.6. Espero que lo podamos resolver para continuar con la integración con la rama master y oficializar este nuevo release.

Cuéntame que opinas

Saludos

**Comment by apradoc** [comment]
Hola @snaphuman . Estoy de acuerdo con tu observación. En la Asamblea acordamos en algún momento que el compañero César estaría atento del Foro del sitio. Le informaré con referencia a este issue

**Comment by snaphuman** [comment]
Vale @apradoc entonces cerraré este incidente para completar el mileston. Nos leemos en la lista!
