### ISSUE TITLE
Aumentar el z-index del Tooltip en el panel de administración

### ISSUE THREAD

**Issue by apradoc** [JokteLatinoamerica/jokte-cms#65]
El texto del menú del panel de administración se superpone al tooltip descriptivo.
![captura de pantalla de 2014-12-17 03 58 23](https://cloud.githubusercontent.com/assets/92080/5468488/c6e6de16-85a1-11e4-95c6-b3a5165127b9.png)

**Comment by snaphuman** [comment]
Incluido en milestone para Jeyuu v1.3.6
