### ISSUE TITLE
El parámetro 'float' en los artículos se anula en la plantilla Jokte Antu

### ISSUE THREAD

**Issue by apradoc** [JokteLatinoamerica/jokte-cms#66]
Al aplicar el parámetro 'float: left' en el editor de texto se visualiza correctamente 
![mi sitio jokte - administracion - gestor de articulos editar un articulo 2014-12-17 04-09-47](https://cloud.githubusercontent.com/assets/92080/5468576/50f55226-85a3-11e4-83a2-391d5f5f52ed.png)

Luego en la plantilla Antu el parámetro no se ve aplicado.
![articulo 2014-12-17 04-08-32](https://cloud.githubusercontent.com/assets/92080/5468579/6a0f4fe6-85a3-11e4-9cc9-f00cedefc31c.png)

Al cambiar de plantilla - Joomspirit99 - el parámetro cumple su función,
![articulo 2014-12-17 04-06-05](https://cloud.githubusercontent.com/assets/92080/5468585/8c064c76-85a3-11e4-88a5-5128d21460ad.png)

Algun parámetro 'clear: both' de los contenedores de los artículos debe estar anulando el parámetro float en los artículos en la plantilla Jokte Antu.

**Comment by snaphuman** [comment]
Incluido en milestone para Jeyuu v1.3.6
