### ISSUE TITLE
Mensaje de actualización menciona Joomla! en vez de Jokte!

### ISSUE THREAD

**Issue by apradoc** [JokteLatinoamerica/jokte-cms#68]
En el  panel de administración el icono rápido de actualizacion muestra los mensajes de actualizado/no actualizado con el nombre Joomla! en vez de Jokte!
![indice](https://cloud.githubusercontent.com/assets/92080/6477246/3da1f27e-c1f3-11e4-868c-e2bd1a8d00a7.png)

**Comment by fastslack** [comment]
@apradoc como puedo enviar un Pull Request? O necesito si o si permisos dentro de Jokte! para arreglar issues?

Cuando trato de hacer un fork de Jokte! me redirije a un fork de Joomla!

**Comment by snaphuman** [comment]
Hola Matias
En el repo de Jokte! aun no aparece registrado tu Pull Request.
Intenta clonar el repo y te agrego como colaborador para que no tengas problema en hacer push

Saludos

**Comment by snaphuman** [comment]
Ya estás dentro del grupo de colaboradores

**Comment by fastslack** [comment]
Ya acepte la invitacion. Este bug ya esta arreglado? Lo reabro

**Comment by snaphuman** [comment]
So siento, no estaba arreglado, cerré el issue accidentalmente.

**Comment by fastslack** [comment]
No hay problema. Ocurre que tengo un problema cuando hago un pull request. A mi no me deja hacer un fork directamente de jokte, sino que me redirije a joomla-cms. 

Como es el procedimiento que haces vos para enviar un pull request?

**Comment by fastslack** [comment]
Ahi pude, hay que tener mucho cuidado por que por default esta seteado el repositorio de joomla-cms. Voy a ver la forma de cambiar eso y que quede por defecto el repositorio de jokte-cms

**Comment by snaphuman** [comment]
Si tienes razón, gracias por cambiar el repo default. Dale, adelante con el Pull Request

**Comment by apradoc** [comment]
Gracias @snaphuman por ayudar y darle la Bienvenida a nuestro hermano @fastslack a su casa de siempre.
