### ISSUE TITLE
Etiqueta de mensaje COM_USER_NOTES 

### ISSUE THREAD

**Issue by apradoc** [JokteLatinoamerica/jokte-cms#72]
Aunque la etiqueta está presente en la línea 169 de jokte-cms/administrator/language/es-LA/es-LA.com_users.ini la etiqueta se muestra sin referencia 
![usernotes](https://cloud.githubusercontent.com/assets/92080/7473022/a15fc734-f301-11e4-9c60-44c591e0a7b5.png)

**Comment by snaphuman** [comment]
La cadena COM_USERS_NOTES corresponde al texto alternativo de la
imágen que representa el filtrado de notas en la administración de usuarios.

En este issue la imagen no existía por lo que recaía en el texto
alternativo sin traducción.

Se implementa JText:: para traducir la cadena y se reutiliza la imágen
de filtro de notas de la plantilla hator en storkantu


2015-05-05 8:05 GMT-05:00 Adrián Prado <notifications@github.com>:

> Aunque la etiqueta está presente en la línea 169 de
> jokte-cms/administrator/language/es-LA/es-LA.com_users.ini la etiqueta se
> muestra sin referencia
> [image: usernotes]
> <https://cloud.githubusercontent.com/assets/92080/7473022/a15fc734-f301-11e4-9c60-44c591e0a7b5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JokteLatinoamerica/jokte-cms/issues/72>.
>



-- 
Fabián Hernández
@snaphuman <http://twitter.com/snaphuman>
Web & Front end developer
** Jokte! **
LatinoAmerica
