### ISSUE TITLE
Alias de menú no se guarda bien al crear un tipo de menú "Crear una URL"

### ISSUE THREAD

**Issue by henryseron** [JokteLatinoamerica/jokte-cms#79]
He creado un elemento de menú como se muestra en la imagen a continuación:
![image](https://cloud.githubusercontent.com/assets/11153444/9032736/a792c492-398f-11e5-9e51-0cc241a1e9a5.png)

El tipo de elemento es "Crear una URL", nombre "Pesca Recreativa" y url "#". Este tipo de menú lo utilizo como elemento de menú "separador" (el motivo de usar este tipo de elemento y no el elemento separador es motivo aparte.)

Cae mencionar que tengo habilitadas las URL amigables en el sitio web. Cuando guardo este tipo de elemento de menú, y luego reviso la URL en el front-end obtengo lo siguiente:

![image](https://cloud.githubusercontent.com/assets/11153444/9032796/402eaba8-3990-11e5-82d3-ebcee2b0d5ce.png)

La URL que debería obtener es http://www.turismoaltopalena.cl/jokte/pesca-recreativa/enlaces-de-interes.html, en lugar de eso tengo http://www.turismoaltopalena.cl/jokte/2015-07-06-06-39-42/enlaces-de-interes.html. Si miramos con cuidado el "alias" pesca-recreativa no está, por el contrario tengo la fecha y hora de creación del elemento de menú.

Cuando regreso al back-end  editar dicho ítem de menú, lo que hago es cambiar el tipo de elemento de menú de "Crear una URL" a "Crear un separador" o cualquier otro y aparece lo siguiente:

![image](https://cloud.githubusercontent.com/assets/11153444/9032846/bc5f75fe-3990-11e5-924e-ec66627f61ab.png)

En la imagen anterior se puede ver como el alias es la fecha y hora de creación del elemento de menú del tipo "Crear una URL", en lugar de ser el nombre del ítem en minúsculas con los espacios reemplazados por un guión.

Para solucionar el problema del alias cambio manualmente a lo que yo quiero que aparezca (pesca-recreativa):

![image](https://cloud.githubusercontent.com/assets/11153444/9032912/1ccf878a-3991-11e5-91ee-0bbf0b9810ad.png)

Luego de guardar regreso nuevamente el tipo de elemento de menú de "Crear un separador" a "Crear una URL", ya que el alias que puse de forma manual se guardo anteriormente y ahora ya tengo la url amigable de forma correcta:

![image](https://cloud.githubusercontent.com/assets/11153444/9032954/588d5694-3991-11e5-95a5-366734dec141.png)

En resumen, no se guarda bien el alias del elemento de menú cuando este es del tipo "Crear una URL".

**Comment by tuxmerlin** [comment]
Si era un error heredado de Joomla. Ya está arreglado
https://github.com/JokteLatinoamerica/jokte-cms/commit/c1a21bdb0990a0e2e523199aba585d6b23283970
